# Generated by Django 5.0.1 on 2024-02-02 16:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=50, verbose_name='Familiya')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Manzil')),
                ('akex_id', models.IntegerField(blank=True, default='', null=True, verbose_name='KARGO ID')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon Raqam')),
                ('pinfl', models.CharField(max_length=14, null=True, verbose_name='PINFL Raqam')),
                ('sp', models.CharField(blank=True, max_length=7, verbose_name='Pasport Seriya')),
                ('avatar', models.ImageField(default='avatar.png', upload_to='users/avatars/', verbose_name='Avatar')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
