# Generated by Django 5.0.2 on 2024-02-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_akex_id_alter_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='akex_id',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='KARGO ID'),
        ),
    ]
