# Generated by Django 5.0.2 on 2024-02-18 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_address_profile_telegram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pinfl',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sp',
        ),
        migrations.CreateModel(
            name='AkexId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinfl', models.CharField(max_length=14)),
                ('sp', models.CharField(max_length=7)),
                ('image', models.ImageField(upload_to='akex_id/passports/')),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
