# Generated by Django 5.0.2 on 2024-02-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_pinfl_remove_profile_sp_akexid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='akexid',
            options={'ordering': ('-created',), 'verbose_name': 'AkexID', 'verbose_name_plural': 'AkexID'},
        ),
    ]
