# Generated by Django 5.0.2 on 2024-02-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_akexid_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='akex_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Xitoy Manzil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Uy manzil'),
        ),
    ]
